<?php

namespace App\Enums;

enum FormStatus
{
    CONST FORM_SUBMITTED = 1;
    CONST FORM_APPROVED_BY_REVIEWER = 2;
    CONST FORM_REJECTED_BY_REVIEWER = 3;
    CONST FORM_APPROVED_BY_DIRECTOR = 4;
    CONST FORM_REJECTED_BY_DIRECTOR = 5;
}